"""Story-010: real-SIESTA-data validation (Si diamond, committed fixtures).

Fixtures: 2-atom primitive + 8-atom conventional supercell of Si (SZ,
PBE), generated by ``examples/si_example/regenerate_fixtures.sh`` on
nic6 (SIESTA 5.1 perspin). Files are ~140 KB total.

Sealed here:

1. HSX parsing through HamiltonIO's SislParser with the supercell
   translations taken from the Hamiltonian file (Rlist fix).
2. Unfolded weight sums over the complete commensurate grid at Gamma
   (pristine groups exactly 0/1/2) on the real 8-atom supercell with a
   skew (non-diagonal) supercell matrix
   B = [[-1,1,1],[1,-1,1],[1,1,-1]].

The generic-k behaviour is covered by two weight definitions
(``compute(method=...)``): the exact torus projection (ring) and the
standard Popescu-Zunger/Lee ideal weight, sealed against the
primitive-table oracle and the synthetic multi-shell fixture
(test_synth_kgrid). See notes/weight-definitions.md in the project
vault.
"""
import numpy as np
import pytest
from scipy.linalg import eigh

import os

import numpy as np
import pytest

DATA = os.path.join(os.path.dirname(__file__), "data", "si_example")


def _torus_parser(fdf_name):
    from HamiltonIO.siesta.sisl_wrapper import SislParser

    class TorusSislParser(SislParser):
        """Rlist from the HS file's actual supercell translations."""

        def read_Rlist(self, geom=None):
            return self.ham.lattice.sc_off

    return TorusSislParser(os.path.join(DATA, fdf_name))


@pytest.fixture(scope="module")
def si_models():
    pytest.importorskip("HamiltonIO")
    pytest.importorskip("sisl")
    pp = _torus_parser("si_prim.fdf")
    ps = _torus_parser("si_sc.fdf")
    return pp.get_model(), ps.get_model()


def test_primitive_eigenvalues_reasonable(si_models):
    """The parsed primitive model diagonalizes to Si-like valence bands."""
    prim = si_models[0]
    out = prim.HS_and_eigen(np.atleast_2d(np.array([0.0, 0.0, 0.0])))
    H, S = np.asarray(out[0]), np.asarray(out[1])
    eps = eigh(H[0], S[0], eigvals_only=True)
    assert len(eps) == 8  # 2 atoms x 4 SZ orbitals
    assert eps[0] < -10.0 < eps[3] < 5.0  # valence s deep, p near gap


def test_primitive_matches_siesta_eig(si_models):
    """Seal against SIESTA-native eigenvalues (.EIG at the SCF Gamma).

    The code's Gamma eigenvalues plus the Fermi energy recorded in the
    .EIG header reproduce SIESTA's bands to file precision. (This also
    certifies the HSX parsing: no k-convention is involved at Gamma.)
    """
    prim = si_models[0]
    out = prim.HS_and_eigen(np.atleast_2d(np.array([0.0, 0.0, 0.0])))
    H, S = np.asarray(out[0]), np.asarray(out[1])
    eps = eigh(H[0], S[0], eigvals_only=True)

    eig_path = os.path.join(DATA, "si_prim.EIG")
    with open(eig_path) as fh:
        lines = fh.readlines()
    e_fermi = float(lines[0])
    tokens = lines[2].split()
    siesta_evals = np.array([float(v) for v in tokens[-len(eps):]])
    assert len(siesta_evals) == len(eps)
    assert np.abs((eps + e_fermi) - siesta_evals).max() < 1e-4


def test_wfsx_gamma_eigenvalues_match(si_models):
    """SIESTA-native WFSX eigenvalues at Gamma match the parsed H,S.

    The first WaveFuncKPoints entry is Gamma (convention-free). WFSX
    energies carry SIESTA's Fermi shift, added here from the .EIG
    header, so agreement certifies the WFSX leg end to end.
    """
    import sisl

    prim = si_models[0]
    out = prim.HS_and_eigen(np.atleast_2d(np.zeros(3)))
    H, S = np.asarray(out[0]), np.asarray(out[1])
    eps = eigh(H[0], S[0], eigvals_only=True)

    with open(os.path.join(DATA, "si_prim.EIG")) as fh:
        e_fermi = float(fh.readlines()[0])

    wfsx = sisl.get_sile(os.path.join(DATA, "si_prim.selected.WFSX"))
    evals_w = [np.asarray(wfc.c, dtype=float) for wfc in wfsx.yield_eigenstate()]
    # entry 0 is the Gamma point (first requested k); WFSX energies are
    # Fermi-shifted, so the absolute eigenvalue = raw - E_fermi
    assert np.abs(np.sort(evals_w[0] - e_fermi) - np.sort(eps)).max() < 1e-4


def test_skew_supercell_gamma_group_weights(si_models):
    """Pristine 8-atom SC unfolding at Gamma: group weights exactly 0/1/2."""
    from unfolding.lcao_unfolder import HamiltonIOModel, LCAOUnfolder
    from unfolding.mapping import RelabelMap

    prim, sc = si_models
    B = np.array([[-1, 1, 1], [1, -1, 1], [1, 1, -1]])
    assert np.allclose(
        B @ np.asarray(prim.atoms.cell), np.asarray(sc.atoms.cell), atol=1e-6
    )
    rm = RelabelMap.from_atoms(
        sc.atoms, prim.atoms, B, orb_counts_sc=[4] * 8, orb_counts_prim=[4, 4]
    )
    unf = LCAOUnfolder(HamiltonIOModel(sc), rm)
    res = unf.compute(np.array([[0.0, 0.0, 0.0]]))
    e, w = res.eigenvalues[0], res.weights[0]
    start = 0
    for i in range(1, len(e) + 1):
        if i == len(e) or e[i] - e[i - 1] > 1e-6:
            g = w[start:i].sum()
            assert abs(g - round(g)) < 1e-6, (start, i, g)
            start = i


def _group_sums(eps, w, tol=1e-8):
    """Sum weights within exactly-degenerate eigenvalue groups."""
    order = np.argsort(eps)
    out = []
    i = 0
    while i < len(eps):
        j = i
        while j < len(eps) and abs(eps[order[j]] - eps[order[i]]) < tol:
            j += 1
        out.append(float(np.sum(w[order[i:j]])))
        i = j
    return sorted(out)


def test_wfsx_gamma_weights_oracle(si_models):
    """WFSX eigenvector oracle: unfolding weights computed from the
    SIESTA-native WFSX coefficients (independent eigenvector source)
    match the HSX-diagonalization path per degenerate eigenvalue group."""
    import sisl

    prim, sc = si_models
    from unfolding.lcao_unfolder import HamiltonIOModel, LCAOUnfolder
    from unfolding.mapping import RelabelMap

    B = np.array([[-1, 1, 1], [1, -1, 1], [1, 1, -1]])
    rm = RelabelMap.from_atoms(
        sc.atoms, prim.atoms, B, orb_counts_sc=[4] * 8, orb_counts_prim=[4, 4]
    )
    unf = LCAOUnfolder(HamiltonIOModel(sc), rm)
    res = unf.compute(np.array([[0.0, 0.0, 0.0]]))

    st = sisl.get_sile(os.path.join(DATA, "si_sc.selected.WFSX")).read_eigenstate()
    C = np.asarray(st.state).T.astype(complex)  # (n_orb, n_bands)
    e_st = np.asarray(st.c, dtype=float)
    with open(os.path.join(DATA, "si_prim.EIG")) as fh:
        e_fermi = float(fh.readlines()[0])
    # the SC WFSX energies are Fermi-shifted like the prim ones
    out = sc.HS_and_eigen(np.atleast_2d(np.zeros(3)))
    Hs, Ss = np.asarray(out[0]), np.asarray(out[1])
    eps_sc = eigh(Hs[0], Ss[0], eigvals_only=True)
    shift = np.sort(eps_sc - np.sort(e_st))[0]
    e_st = e_st + shift

    A = unf._bra_overlap(np.zeros(3))
    G = unf._sector_gram_block(np.zeros(3), np.zeros(3))
    c = A @ C
    x = np.linalg.solve(G, c)
    w_wfsx = np.real(np.sum(np.conj(c) * x, axis=0))

    def run_sums(e, w, tol=1e-6):
        """Weight sums over consecutive eigenvalue runs (the same grouping
        as the Gamma group-seal test above)."""
        order = np.argsort(e)
        e_s, w_s = e[order], w[order]
        out, start = [], 0
        for i in range(1, len(e_s) + 1):
            if i == len(e_s) or e_s[i] - e_s[i - 1] > tol:
                out.append(float(w_s[start:i].sum()))
                start = i
        return out

    e_u = np.sort(e_st)
    assert np.abs(e_u - np.sort(res.eigenvalues[0])).max() < 1e-4
    gr = run_sums(res.eigenvalues[0], res.weights[0])
    gw = run_sums(e_st, w_wfsx)
    assert np.abs(np.array(gr) - np.array(gw)).max() < 1e-6, (gr, gw)
    # the SIESTA-native states are exact folded states: clean 0/1 weights
    assert np.abs(w_wfsx - np.round(w_wfsx)).max() < 1e-6, w_wfsx
