"""Story-010: real-SIESTA-data validation (Si diamond, committed fixtures).

Fixtures: 2-atom primitive + 8-atom conventional supercell of Si (SZ,
PBE), generated by ``examples/si_example/regenerate_fixtures.sh`` on
nic6 (SIESTA 5.1 perspin). Files are ~140 KB total.

Sealed here:

1. HSX parsing through HamiltonIO's SislParser with the supercell
   translations taken from the Hamiltonian file (Rlist fix).
2. Unfolded weight sums over the complete commensurate grid at Gamma
   (pristine groups exactly 0/1/2) on the real 8-atom supercell with a
   skew (non-diagonal) supercell matrix
   B = [[-1,1,1],[1,-1,1],[1,1,-1]].

KNOWN OPEN DEFECT (not asserted here): at generic (non-commensurate)
k the weights deviate by up to ~0.1 for this skew supercell; the
phase conventions were validated on diagonal supercell matrices only.
Tracked in story-010 of the project vault.
"""
import numpy as np
import pytest
from scipy.linalg import eigh

import os

import numpy as np
import pytest

DATA = os.path.join(os.path.dirname(__file__), "data", "si_example")


def _torus_parser(fdf_name):
    from HamiltonIO.siesta.sisl_wrapper import SislParser

    class TorusSislParser(SislParser):
        """Rlist from the HS file's actual supercell translations."""

        def read_Rlist(self, geom=None):
            return self.ham.lattice.sc_off

    return TorusSislParser(os.path.join(DATA, fdf_name))


@pytest.fixture(scope="module")
def si_models():
    pp = _torus_parser("si_prim.fdf")
    ps = _torus_parser("si_sc.fdf")
    return pp.get_model(), ps.get_model()


def test_primitive_eigenvalues_reasonable(si_models):
    """The parsed primitive model diagonalizes to Si-like valence bands."""
    prim = si_models[0]
    out = prim.HS_and_eigen(np.atleast_2d(np.array([0.0, 0.0, 0.0])))
    H, S = np.asarray(out[0]), np.asarray(out[1])
    eps = eigh(H[0], S[0], eigvals_only=True)
    assert len(eps) == 8  # 2 atoms x 4 SZ orbitals
    assert eps[0] < -10.0 < eps[3] < 5.0  # valence s deep, p near gap


def test_skew_supercell_gamma_group_weights(si_models):
    """Pristine 8-atom SC unfolding at Gamma: group weights exactly 0/1/2."""
    from unfolding.lcao_unfolder import HamiltonIOModel, LCAOUnfolder
    from unfolding.mapping import RelabelMap

    prim, sc = si_models
    B = np.array([[-1, 1, 1], [1, -1, 1], [1, 1, -1]])
    assert np.allclose(
        B @ np.asarray(prim.atoms.cell), np.asarray(sc.atoms.cell), atol=1e-6
    )
    rm = RelabelMap.from_atoms(
        sc.atoms, prim.atoms, B, orb_counts_sc=[4] * 8, orb_counts_prim=[4, 4]
    )
    unf = LCAOUnfolder(HamiltonIOModel(sc), rm)
    res = unf.compute(np.array([[0.0, 0.0, 0.0]]))
    e, w = res.eigenvalues[0], res.weights[0]
    start = 0
    for i in range(1, len(e) + 1):
        if i == len(e) or e[i] - e[i - 1] > 1e-6:
            g = w[start:i].sum()
            assert abs(g - round(g)) < 1e-6, (start, i, g)
            start = i
