"""Story-010 real spin-orbit SIESTA fixture check.

The FePt fixture was generated by the SIESTA spin-orbit branch on nic6
with full-relativistic Fe/Pt pseudopotentials. This test deliberately
only validates the WFSX leg: that branch does not emit HSX for the
spin-orbit run, so the LCAO weight path remains covered by the story-009
spinor toy and the real collinear HSX fixtures.
"""
import os

import numpy as np
import pytest

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA = os.path.join(ROOT, "tests", "data", "fept_spinor")


def test_real_spinor_wfsx_is_complex_and_complete():
    sisl = pytest.importorskip("sisl")
    with open(os.path.join(DATA, "fept_spinor.fdf")) as fh:
        text = fh.read()
    assert "Spin Spin-Orbit" in text

    wfsx = sisl.get_sile(os.path.join(DATA, "fept_spinor.selected.WFSX"))
    kpts, spins, nstates = wfsx.read_info()
    assert kpts.shape == (1, 3)
    assert nstates.tolist() == [[36]]
    state = wfsx.read_eigenstate()
    assert state.state.shape == (36, 36)
    assert np.iscomplexobj(state.state)
    assert np.isfinite(state.state).all()
    assert np.isfinite(state.c).all()
