"""GPAW-backend end-to-end validation on real fixtures (story 017).

Fixtures: ``tests/data/gpaw_example/*.gpw`` generated by
``examples/gpaw_si/generate_fixtures.py`` (gpaw >= 26 new calculators,
serial, PBE, Gamma-centered grids; see that script for run parameters).

Sealed here:

1. LCAO route: the pristine 8-atom conventional cell, unfolded onto the
   primitive fcc path with supercell matrix B. At Gamma the degenerate
   group weight sums are exact integers totalling 8 (= primitive orbital
   count), and at a generic k the ideal weights are binary 0/1.
2. The supercell Gamma spectrum is the primitive Gamma spectrum four
   times (host bands match the GPAW primitive-cell band structure).
3. Si:P (match_species=False, P carries 4 AOs/atom like Si): Parseval
   total weight 8 at Gamma, every group weight in [0, 2], and at least
   one genuinely fractional group (the dopant signature).
4. Planewave route: the pristine conventional-cell path run unfolds to
   strictly binary weights at generic k.
"""
import os

import numpy as np
import pytest

DATA = os.path.join(os.path.dirname(__file__), "data", "gpaw_example")
B = np.array([[-1, 1, 1], [1, -1, 1], [1, 1, -1]])  # conv cell = B @ prim cell

# fcc special points in primitive reciprocal fractional coordinates
SPECIAL = {
    "G": (0.0, 0.0, 0.0), "X": (0.5, 0.0, 0.5),
    "W": (0.5, 0.25, 0.75), "L": (0.5, 0.5, 0.5),
}
PATH = "GXWGLWX"


def _group_sums(evals, weights, tol=1e-6):
    """Weight sums over consecutive (energy-sorted) degenerate runs."""
    order = np.argsort(evals)
    e, w = evals[order], weights[order]
    out, start = [], 0
    for i in range(1, len(e) + 1):
        if i == len(e) or e[i] - e[i - 1] > tol:
            out.append(float(w[start:i].sum()))
            start = i
    return np.array(out)


def _require_fixture(name):
    path = os.path.join(DATA, name)
    if not os.path.exists(path):
        pytest.skip(f"fixture missing: {name} (run examples/gpaw_si/"
                    "generate_fixtures.py)")
    return path


@pytest.fixture(scope="module")
def lcao():
    pytest.importorskip("gpaw")
    pytest.importorskip("HamiltonIO")
    from HamiltonIO.gpaw import GpawLcaoModel
    from unfolding.lcao_unfolder import LCAOUnfolder
    from unfolding.mapping import RelabelMap

    prim = GpawLcaoModel.from_file(_require_fixture("si_prim_lcao.gpw"))
    sc = GpawLcaoModel.from_file(_require_fixture("si_sc_lcao.gpw"))
    rm = RelabelMap.from_atoms(
        sc.atoms, prim.atoms, B,
        orb_counts_sc=[4] * 8, orb_counts_prim=[4, 4],
    )
    return prim, sc, LCAOUnfolder(sc, rm)


@pytest.fixture(scope="module")
def si7p():
    pytest.importorskip("gpaw")
    pytest.importorskip("HamiltonIO")
    from HamiltonIO.gpaw import GpawLcaoModel
    from unfolding.lcao_unfolder import LCAOUnfolder
    from unfolding.mapping import RelabelMap

    prim = GpawLcaoModel.from_file(_require_fixture("si_prim_lcao.gpw"))
    sc = GpawLcaoModel.from_file(_require_fixture("si7p_lcao.gpw"))
    # P substitutes a host site: match_species=False, equal orbital counts
    rm = RelabelMap.from_atoms(
        sc.atoms, prim.atoms, B,
        orb_counts_sc=[4] * 8, orb_counts_prim=[4, 4],
        match_species=False,
    )
    return prim, sc, LCAOUnfolder(sc, rm)


@pytest.fixture(scope="module")
def pw():
    pytest.importorskip("gpaw")
    pytest.importorskip("HamiltonIO")
    from HamiltonIO.gpaw import GpawPWParser
    from unfolding.pw_unfolder import PWEigenData, PWUnfolder

    path = _require_fixture("si8_pw.gpw")
    data = GpawPWParser(path).read()
    eigendata = PWEigenData(
        kpoints=data.kpoints,
        gvecs=data.gvecs,
        coefficients=[c[None, :, None, :] for c in data.coefficients],
        eigenvalues=data.eigenvalues[:, None, :],
    )
    # request primitive points mapped back from the stored supercell path
    # (the fixture samples the 300-point Gamma-X-W-Gamma-L-W-X path)
    kprim = data.kpoints @ np.linalg.inv(B)
    return data, PWUnfolder(eigendata, B), kprim


def test_lcao_gamma_group_sums_are_integers(lcao):
    """Pristine Gamma: exact-integer degenerate group weights summing to 8."""
    prim, sc, unf = lcao
    res = unf.compute(np.zeros((1, 3)), method="ring")
    total = res.weights[0].sum()
    assert abs(total - 8.0) < 1e-6
    sums = _group_sums(res.eigenvalues[0], res.weights[0])
    assert np.abs(sums - np.round(sums)).max() < 1e-6
    # each group carries an integer multiple of the single-fold weight
    assert sums.min() > -1e-8 and sums.max() < 4 + 1e-8


def test_lcao_generic_k_binary(lcao):
    """Pristine generic-k ideal weights are 0/1 to the table accuracy.

    Nyquist-shell splitting keeps the interpolated overlap Hermitian;
    finite orbital/shell coverage still limits generic-k precision.
    The plane-wave route below seals much sharper binary weights.
    """
    prim, sc, unf = lcao
    kg = np.array([[0.137, 0.062, 0.0]])
    res = unf.compute(kg, method="ideal")
    w = res.weights[0]
    assert np.abs(w * (1.0 - w)).max() < 0.05
    assert abs(w.sum() - 8.0) < 1e-3


def test_lcao_gamma_bands_match_primitive(lcao):
    """SC Gamma spectrum = primitive bands at the four star k-points.

    The star of the conventional-cell Gamma contains Gamma and the three
    X points of the primitive lattice; their primitive bands must appear
    in the supercell Gamma spectrum up to the potential-reference
    difference between the two independent GPAW runs.
    """
    from scipy.linalg import eigh

    prim, sc, unf = lcao
    h_sc, s_sc = sc.hs_and_eigen([0.0, 0.0, 0.0])
    e_sc = np.sort(eigh(h_sc, s_sc, eigvals_only=True))
    star = [(0, 0, 0), (0, 0.5, 0.5), (0.5, 0, 0.5), (0.5, 0.5, 0)]
    ref = np.sort(np.concatenate([
        np.sort(eigh(*prim.hs_and_eigen(k), eigvals_only=True)) for k in star
    ]))
    assert e_sc.shape == ref.shape
    assert np.abs(e_sc - ref).max() < 0.1


def test_si7p_gamma_parseval_and_defect_weight(si7p):
    """Si:P Gamma: near-Parseval total, bounded groups, fractional groups.

    On the defect supercell the single-k weight sum need not be exactly
    the primitive orbital count (translation symmetry is broken), so the
    total carries a small deficit; the dopant signature is the set of
    genuinely fractional degenerate-group weights.
    """
    prim, sc, unf = si7p
    res = unf.compute(np.zeros((1, 3)), method="ring")
    w = res.weights[0]
    assert abs(w.sum() - 8.0) < 0.1
    sums = _group_sums(res.eigenvalues[0], res.weights[0])
    assert sums.min() > -1e-3 and sums.max() < 4 + 1e-3
    fractional = sums[(sums > 1e-2) & (sums < 1.0 - 1e-2)]
    assert fractional.size >= 3, "too few fractional groups: dopant signature lost"


def test_pw_generic_k_binary(pw):
    """Planewave unfolding of the pristine path is strictly binary.

    The four highest stored bands are excluded: top-of-bank states of
    the path SCF converge loosely and their coefficients are not
    trustworthy to binary-weight accuracy; every resolved band (16
    occupied + 4 conduction) is binary to 1e-4.
    """
    data, unf, kprim = pw
    res = unf.compute(kprim[::7], resolve_degenerate=1e-3)
    w = res.weights[:, :20]
    assert np.abs(w * (1.0 - w)).max() < 1e-4
    # every requested point found its stored SC momentum
    assert res.sc_kpoints.shape == kprim[::7].shape

def test_pw_si7p_gamma_fold_partition_and_fractional_donor():
    """A real Si:P PW Gamma eigenstate partitions over four folds."""
    pytest.importorskip("gpaw")
    from HamiltonIO.gpaw import GpawPWParser
    from unfolding.pw_unfolder import PWEigenData, PWUnfolder

    data = GpawPWParser(_require_fixture("si7p_pw.gpw")).read()
    eigen = PWEigenData(data.kpoints, data.gvecs,
                        [c[None, :, None, :] for c in data.coefficients],
                        data.eigenvalues[:, None, :])
    folds = [[0, 0, 0], [0, .5, .5], [.5, 0, .5], [.5, .5, 0]]
    result = PWUnfolder(eigen, B).compute(folds)
    np.testing.assert_allclose(result.weights.sum(axis=0), 1, atol=1e-12)
    donor = result.weights[:, 16]
    assert donor.min() > 0.05 and donor.max() < 0.4
