"""Story-010 real spin-orbit SIESTA fixture check.

The FePt fixture was generated by the SIESTA spin-orbit branch on nic6
with full-relativistic Fe/Pt pseudopotentials. This test deliberately
only validates the WFSX leg: that branch does not emit HSX for the
spin-orbit run, so the LCAO weight path remains covered by the story-009
spinor toy and the real collinear HSX fixtures.
"""
import os

import numpy as np
import pytest

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA = os.path.join(ROOT, "tests", "data", "fept_spinor")


def _first_eig_values(path, nstates):
    """Read the first k-point's energies from a SIESTA EIG file."""
    with open(path) as fh:
        lines = fh.readlines()
    values = []
    for line in lines[2:]:
        fields = line.split()
        if not fields:
            continue
        # A new k-point line starts with its integer index; continuation
        # lines contain only energy values.
        start = 1 if len(values) == 0 and fields[0].isdigit() else 0
        values.extend(float(x) for x in fields[start:])
        if len(values) >= nstates:
            break
    return np.asarray(values[:nstates])


def test_real_spinor_wfsx_is_complex_and_complete():
    sisl = pytest.importorskip("sisl")
    with open(os.path.join(DATA, "fept_spinor.fdf")) as fh:
        text = fh.read()
    assert "Spin Spin-Orbit" in text

    wfsx = sisl.get_sile(os.path.join(DATA, "fept_spinor.selected.WFSX"))
    kpts, spins, nstates = wfsx.read_info()
    assert kpts.shape == (1, 3)
    assert nstates.tolist() == [[36]]
    state = wfsx.read_eigenstate()
    assert state.state.shape == (36, 36)
    assert np.iscomplexobj(state.state)
    assert np.isfinite(state.state).all()
    assert np.isfinite(state.c).all()


def test_real_spinor_wfsx_eigenvalues_match_eig():
    """The spin-orbit WFSX energies agree with SIESTA's EIG record."""
    sisl = pytest.importorskip("sisl")
    state = sisl.get_sile(
        os.path.join(DATA, "fept_spinor.selected.WFSX")
    ).read_eigenstate()
    eig = _first_eig_values(
        os.path.join(DATA, "fept_spinor.EIG"), len(state.c)
    )
    assert len(eig) == len(state.c)
    # WFSX.c and EIG carry the same Fermi-shifted absolute values in this
    # spin-orbit branch; the EIG header is not subtracted a second time.
    assert np.abs(np.sort(np.asarray(state.c)) - np.sort(eig)).max() < 1e-4
