"""Unfolding example: fcc Cu phonons from an Abinit DDB.

This example documents the *frame chain* of the k-path, which is where the
subtlety lies:

1. The DDB file ``out_DDB`` was computed for the **conventional cubic** fcc
   cell (natom=4, cubic rprim -- inspect it with ``abiopen('./out_DDB')``).
   Everything downstream of abipy therefore lives in the fractional
   reciprocal basis of that conventional cell (units 2*pi/a, with
   X=(0,1,0), W=(1/2,1,0), L=(1/2,1/2,1/2), ...):

   - ``kpath_bounds`` passed as ``qptbounds`` to ``anaget_phbst_and_phdos_files``
     are interpreted in the DDB structure's fractional coordinates, and
   - the ``qpoints`` returned in the PHBST file come back in the same
     conventional fractional frame and are forwarded as-is to
     ``phonon_unfolder`` (they only matter there if ``phase=True``; the
     spectral weights are built from the eigenvectors and the translation
     lattice generated by ``sc_mat``, in DDB-cell units).

2. ase's ``get_special_points`` for the primitive fcc cell returns the
   standard fcc special points in the **primitive-cell fractional** basis
   (Setyawan & Curtarolo): X=(1/2,0,1/2), W=(1/2,1/4,3/4), L=(1/2,1/2,1/2).

3. The two bases are related by the supercell matrix.  Here the supercell is
   the conventional cubic cell written in units of the primitive fcc lattice
   vectors (rows convention ``S = A_prim @ sc_mat``)::

       sc_mat = inv([[0,1,1],[1,0,1],[1,1,0]]/2) = [[-1,1,1],[1,-1,1],[1,1,-1]]

   The same (symmetric) matrix converts fractional k-points between the two
   reciprocal frames: ``k_conv = k_prim @ sc_mat``.  E.g.
   X: (1/2,0,1/2) -> (0,1,0);  W: (1/2,1/4,3/4) -> (1/2,1,0);
   L: (1/2,1/2,1/2) -> (1/2,1/2,1/2).

   This multiplication of the ase points by the supercell matrix is the step
   that must not be skipped: feeding the primitive-frame points straight to
   abipy silently plots the wrong path, because abipy reads them in the
   conventional frame of the DDB.
"""
import numpy as np
from unfolding.DDB_unfolder import DDB_unfolder
import matplotlib.pyplot as plt
from ase.build import bulk
from ase.dft.kpoints import get_special_points


def build_fcc_kpath(sc_mat):
    """Return (kpath_bounds, knames) for G-X-W-G-L in the DDB (conventional) frame.

    ``sc_mat`` is the supercell matrix in primitive-lattice units (rows
    convention ``S = A_prim @ sc_mat``); its transpose converts primitive
    fractional k-points to conventional fractional ones, and since this
    particular ``sc_mat`` is symmetric, ``k_conv = k_prim @ sc_mat``.
    """
    atoms = bulk('Cu', 'fcc')  # primitive fcc cell, used only for the labels
    points = get_special_points(atoms.cell, eps=0.01)  # primitive fractional coords!
    knames = [r'$\Gamma$', 'X', 'W', r'$\Gamma$', 'L']
    kpath_prim = np.array([points[k] for k in 'GXWGL'])
    # Convert to the conventional-cell frame expected by abipy:
    kpath_bounds = [np.dot(k, sc_mat) for k in kpath_prim]
    # Equivalent explicit conventional-frame path, for reference:
    #   [[0,0,0], [0,1,0], [1/2,1,0], [0,0,0], [1/2,1/2,1/2]]
    return kpath_bounds, knames


def run_unfolding(savefig=None):
    # Supercell: the conventional cubic cell expressed in primitive fcc
    # lattice-vector units (S = A_prim @ sc_mat == a * identity).
    sc_mat = np.linalg.inv((np.array([[0, 1, 1], [1, 0, 1], [1, 1, 0]]) / 2.0))
    kpath_bounds, knames = build_fcc_kpath(sc_mat)
    ax = DDB_unfolder('./out_DDB', sc_mat=sc_mat,
                      kpath_bounds=kpath_bounds, knames=knames)
    if savefig is not None:
        plt.savefig(savefig)
    else:
        plt.show()
    return ax


if __name__ == '__main__':
    run_unfolding()
