"""Normalization identity: sum of spectral weights over the sector equals 1.

Symbolic + numeric derivation of

    sum_{k in K + GZ} W^{KJ}(k) = 1

on the BvK ring toy of ``lcao_weight``:

1. SYMBOLIC: the per-k coefficient tables satisfy, entry-wise,

       sum_{k in sector} M(k)[t, s]  =  S_sc(K)[t, s],

   the Parseval/completeness identity of the dual basis. Hence
   sum_k W(k) = C^dag S_sc C for ANY coefficient vector C.

2. NUMERIC: supercell eigenvectors are S-normalized (C^dag S_sc C = 1 by
   the generalized eigenproblem), so the sector sum is exactly 1 --
   verified over several random fixtures and both supercell momenta.

Writes LaTeX to ``derivations/out/normalization.tex``.
"""
from __future__ import annotations

import sys
from pathlib import Path

if __package__ in (None, ""):  # direct script execution
    sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

import numpy as np
from scipy.linalg import eigh

from derivations.lcao_weight import (
    KS,
    LS,
    NC,
    OUT,
    P,
    RS_SUP,
    make_fixture,
    symbolic_tables,
)


def symbolic_parseval():
    """Assert sum_{k in sector} M(k) == S_sc(K) entry-wise, for both K."""
    import sympy as sp

    for K_sp in ("zero", "half"):
        K_sym = sp.Integer(0) if K_sp == "zero" else sp.pi / 2
        tables, (c0, c4), csyms = symbolic_tables(K_sp)
        cls_sym = {0: c0, 4: c4}
        for d in (1, 2, 3):
            re, im = csyms[d]
            cls_sym[d] = re + sp.I * im
            cls_sym[LS - d] = re - sp.I * im
        S_site = lambda a, b: cls_sym[(b - a) % LS]

        # symbolic supercell overlap matrix S_sc(K)[s, t] with copy phases
        Ssc = sp.zeros(4, 4)
        for s in range(4):
            for t in range(4):
                acc = 0
                for R in RS_SUP:
                    for Rp in RS_SUP:
                        acc += (
                            S_site((R + s) % LS, (Rp + t) % LS)
                            * sp.exp(sp.I * K_sym * ((R - Rp) // NC))
                        )
                Ssc[s, t] = sp.expand(acc / P)

        worst = sp.Integer(0)
        for t in range(4):
            for s in range(4):
                diff = sp.simplify(sum(tables[ik][t, s] for ik in (0, 1)) - Ssc[t, s])
                worst = worst + abs(diff)
        assert worst == 0, (K_sp, worst)
    return Ssc


def run(seeds=(23, 101, 7), atol: float = 1e-10) -> dict:
    OUT.mkdir(parents=True, exist_ok=True)

    # symbolic Parseval identity
    symbolic_parseval()

    # numeric sector sums on independent fixtures
    worst = 0.0
    for seed in seeds:
        fx = make_fixture(seed)
        for K in KS:
            Ssc = fx["sc_matrix"](K, fx["S_site"])
            Hsc = fx["sc_matrix"](K, fx["H_site"])
            ev, V = eigh(Hsc, Ssc)
            for J in range(4):
                C = V[:, J]
                assert abs(np.real(np.conj(C) @ Ssc @ C) - 1.0) < atol
                dk = fx["direct_weights"](C, K)
                worst = max(worst, abs(sum(dk.values()) - 1.0))
    assert worst < atol, worst

    tex = [
        r"% Auto-generated by derivations/normalization.py -- do not edit.",
        r"\section{Sum rule for unfolding weights}",
        r"\begin{equation} \sum_{k = K + G} W^{KJ}_k = 1. \end{equation}",
        r"Symbolic core (Parseval identity of the dual basis):",
        r"\begin{equation} \sum_{k \in \mathrm{sector}} M(k)_{ts} = S^{sc}_{ts}(K),",
        r"\end{equation}",
        r"verified entry-wise by sympy on the BvK ring; hence",
        r"\begin{equation} \sum_k W^{KJ}(k) = C^{\dag} S^{sc}(K) C = 1 \end{equation}",
        rf"for the $S$-normalized eigenstates (numeric worst deviation ${worst:.1e}$).",
    ]
    (OUT / "normalization.tex").write_text("\n".join(tex) + "\n")

    return {"sector_sum_err": worst, "seeds": list(seeds)}


if __name__ == "__main__":
    print(run())
